name: PR checks

##
on:
  push:
    # Trigger the workflow on push event for all branches
    branches:
      -  '**'
  pull_request:
    # Trigger the workflow on pull request event for main branch
    branches:
      - main
jobs:
  workflow:
    name: "Code Formatter and Test cases"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: npm
          cache-dependency-path: src/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Prettier checks
        id: prettier-checks
        run: npx prettier --check .
      - name: On Prettier Success
        if: steps.build.outcome === 'success'
        run: echo "Code is formatted by prettier 🎉"
      - name: On Prettier Failure
        if: steps.prettier-checks.outcome === 'failure'
        run: |
        echo 'Code is not formatted by prettier 😭 but do not worry we got you'
        npx prettier --write .
      - name: Run jest test
        id: jest-test
        run: npn run test
      - name: Test success
        if: steps.jest-test.outcome === 'success'
        run: echo 'All test passed ✅'
      - name: Test failure
        if: steps.jest-test.outcome === 'failure'
        run: echo 'Test failed 🔴'
